name:    learning-haskell
version: 0.1.0.0

dependencies:
- base >= 4.7 && < 5
#- aeson
- text

ghc-options:
- -Wall
- -Wtype-defaults
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  just-learn-haskell-exe:
    main:         Launcher.hs
    source-dirs:  app
    dependencies: [learning-haskell]
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
